#!/bin/bash
source /opt/mos/codebase/bb_bin/common.sh

SVC_LOG="/mnt1/logs/svc.log"

date >> $SVC_LOG
echo 'gunicorn start' >> $SVC_LOG

. /opt/mos/python-env/bin/activate

cd /opt/mos/codebase/starfish-ws

export LANG="en_US.utf8"
export LC_ALL="en_US.UTF-8"
export LC_LANG="en_US.UTF-8"

exec setuidgid mos gunicorn starfish.wsgi:application \
    -w 4 -b 127.0.0.1:3001 \
    -e DJANGO_ENV=prod >> $SVC_LOG 2>&1
