#!/bin/bash
source /opt/mos/codebase/bb_bin/common.sh

SVC_LOG="/mnt1/logs/svc.log"

date >> $SVC_LOG
echo 'yxt_update_data_receiver start' >> $SVC_LOG

. /opt/mos/python-env/bin/activate

export DJANGO_ENV=script_yxt
cd /opt/mos/codebase/starfish-ws/scripts

export LANG="en_US.utf8"
export LC_ALL="en_US.UTF-8"
export LC_LANG="en_US.UTF-8"

exec setuidgid mos python $(py_or_pyc yxt_update_data_receiver.py) >> $SVC_LOG 2>&1
