#!/bin/bash
source /opt/mos/codebase/bb_bin/common.sh

SVC_LOG="/mnt1/logs/svc.log"

date >> $SVC_LOG
echo 'async-set-offline start' >> $SVC_LOG

. /opt/mos/python-env/bin/activate

export DJANGO_ENV=script
cd /opt/mos/codebase/starfish-ws/scripts
exec setuidgid mos python $(py_or_pyc async-set-offline.py) >> $SVC_LOG 2>&1
